name: Playwright Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:

      profile:
        description: "Environment profile"
        required: true
        default: "prod"
        type: choice

        options:
          - prod
          - dev

      tags:
        description: "JUnit Tags"
        required: true
        default: "smoke"
        type: string

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Download Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz

      - name: Extract Allure
        run: |
          tar -zxvf allure-2.29.0.tgz

      - name: Add Allure to PATH
        run: |
          echo "$GITHUB_WORKSPACE/allure-2.29.0/bin" >> $GITHUB_PATH

      - name: Verify Allure Installation
        run: allure --version

      - name: Make run script executable
        run: chmod +x run-tests.sh

      - name: Run Tests

        env:
          PROFILE: ${{ github.event.inputs.profile || 'prod' }}
          TAGS: ${{ github.event.inputs.tags || 'smoke' }}

        run: |
          ./run-tests.sh \
            -P$PROFILE \
            -Dgroups="$TAGS"

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/