name: Playwright Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:

      profile:
        description: "Environment profile"
        required: true
        default: "prod"
        type: choice

        options:
          - prod
          - dev

      tags:
        description: "JUnit Tags"
        required: true
        default: "smoke"
        type: string

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make run script executable
        run: chmod +x run-tests.sh

      - name: Run Tests
        run: |
          ./run-tests.sh \
            -P${{ github.event.inputs.profile }} \
            -Dgroups="${{ github.event.inputs.tags }}"

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/